### ISSUE TITLE
to much services to start without using with_items

### ISSUE THREAD

**Issue by tenhishadow** [lobsterdore/ansible-pdm-mailserver#9]
Hi,
Seems like this:
`
- name: Start rspamd
  service:
    name: rspamd
    state: started

- name: Start rmilter
  service:
    name: rmilter
    state: started

- name: Start opendmarc
  service:
    name: opendmarc
    state: started

- name: Start opendkim
  service:
    name: opendkim
    state: started

- name: Start postfix
  service:
    name: postfix
    state: started

- name: Start dovecot
  service:
    name: dovecot
    state: started

- name: Start nginx
  service:
    name: dovecot
    state: started
`

Can be replaced with 
`
- name: start services
  service: name={{ item }} state=started
  with_items:
    - rspamd
    - rmilter
    - opendmarc
    - opendkim
    - postfix
    - dovecot
    - dovecot
`

**Comment by lobsterdore** [comment]
Excellent point, I can make that change today.

**Comment by lobsterdore** [comment]
Closed by #11

**Comment by tenhishadow** [comment]
Better syntax and enabling services also:

```
- name: starting and enabling service {{ item }}
  service:
    name: "{{ item }}"
	state: "started"
	enabled: "yes"
  with_items:
    - rspamd
    - rmilter
    - opendmarc
    - opendkim
    - postfix
    - dovecot
```
